name: Build and Package Blog

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # run the actionlinter, will fail on errors
      - uses: devops-actions/actionlint@v0.1.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create artifact
        run: |
          tar -czf blog-dist.tar.gz dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog-package
          path: blog-dist.tar.gz
          retention-days: 5
